-- Inicialización se secuencias en 0 

ALTER TABLE amenity AUTO_INCREMENT = 1;
ALTER TABLE cancellation_policy AUTO_INCREMENT = 1;
ALTER TABLE country AUTO_INCREMENT = 1;
ALTER TABLE province AUTO_INCREMENT = 1;
ALTER TABLE canton AUTO_INCREMENT = 1;
ALTER TABLE district AUTO_INCREMENT = 1;
ALTER TABLE classification AUTO_INCREMENT = 1;
ALTER TABLE commentary AUTO_INCREMENT = 1;
ALTER TABLE gender AUTO_INCREMENT = 1;
ALTER TABLE hotel AUTO_INCREMENT = 1;
ALTER TABLE id_type AUTO_INCREMENT = 1;
ALTER TABLE nationality AUTO_INCREMENT = 1;
ALTER TABLE offer AUTO_INCREMENT = 1;
ALTER TABLE payment_method AUTO_INCREMENT = 1;
ALTER TABLE person AUTO_INCREMENT = 1;
ALTER TABLE photo AUTO_INCREMENT = 1;
ALTER TABLE reservation AUTO_INCREMENT = 1;
ALTER TABLE reservation_status AUTO_INCREMENT = 1;
ALTER TABLE review AUTO_INCREMENT = 1;
ALTER TABLE room AUTO_INCREMENT = 1;
ALTER TABLE setting AUTO_INCREMENT = 1;
ALTER TABLE telephone AUTO_INCREMENT = 1;
ALTER TABLE user_type AUTO_INCREMENT = 1;
COMMIT;